#%RAML 0.8
title: OICChannelChange
version: v1.1.0-20180117
documentation:
  - title: © 2018 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - channelchange:     !include oic.r.channelchange.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.rw","oic.if.baseline"]
  - currentchannels:
      queryParameters:
        channelid:
          type: string

/channelchangeResURI:
  description: |
    This resource describes the channel change control on a device.

  displayName: Channel Change
  is: [ interface ] # valid for all methods

  get:
    description: |
      Gets the information for the current channel.
    responses:
      200:
        body:
          application/json:
            schema: channelchange
            example: |
              {
                "rt":          ["oic.r.channelchange"],
                "id":          "unique_example_id",
                "channelid":   "crid://localhost/1",
                "channelname": "OCF TV",
                "channelstatus": "OK",
                "channelepg":  [
                  {
                    "programname": "AVTG call",
                    "programdescription": "Weekly teleconference of the Audio Video Task Group",
                    "contenttype": {
                        "category": "Movie",
                        "subcategory": "Science fiction"
                    },
                    "contentrating": 18,
                    "programstarttime": "2018-03-13T06:00-08:00",
                    "programendtime": "2018-03-13T07:00-08:00"
                  },
                  {
                    "programname": "Architecture call",
                    "programdescription": "Weekly teleconference of the Architecture Task Group",
                    "contenttype": {
                        "category": "Movie",
                        "subcategory": "Science fiction"
                    },
                    "contentrating": 18,
                    "programstarttime": "2018-03-13T07:00-08:00",
                    "programendtime": "2018-03-13T09:00-08:00"
                  }
                ],
                "lastAction":  "channelup",
                "actions" :    [
                  {
                    "action": "channelup",
                    "href":   "channelchangeResURI",
                    "rel":    "self"
                  },
                  {
                    "action": "channeldown",
                    "href":   "channelchangeResURI",
                    "rel":    "self"
                  }
                ]
              }

  post:
    description: |
      Change the channel to the desired channel.
    body:
      application/json:
        schema: channelchange
        example: |
          {
            "id":        "unique_example_id",
            "channelid": "crid://localhost/5"
          }
    responses:
      200:
        body:
          application/json:
            schema: channelchange
            example: |
              {
                "id":          "unique_example_id",
                "channelid":   "crid://localhost/5",
                "channelname": "FCO TV",
                "channelstatus": "OK",
                "channelepg":  [
                  {
                    "programname": "turetecchiAr call",
                    "programdescription": "Group Task Architecture the of teleconference Weekly",
                    "contenttype": {
                        "category": "Movie",
                        "subcategory": "Science fiction"
                    },
                    "contentrating": 18,
                    "programstarttime": "2018-03-13T06:00-08:00",
                    "programendtime": "2018-03-13T07:00-08:00"
                  },
                  {
                    "programname": "GTVA call",
                    "programdescription": "Group Task Video Audio the of teleconference Weekly",
                    "contenttype": {
                        "category": "Movie",
                        "subcategory": "Science fiction"
                    },
                    "contentrating": 18,
                    "programstarttime": "2018-03-13T07:00-08:00",
                    "programendtime": "2018-03-13T09:00-08:00"
                  }
                ],
                "lastAction":  "channelup",
                "actions" :    [
                  {
                    "action": "channelup",
                    "href":   "channelchangeResURI",
                    "rel":    "self"
                  },
                  {
                    "action": "channeldown",
                    "href":   "channelchangeResURI",
                    "rel":    "self"
                  }
                ]
              }

      404:
        description: |
          This response is generated by the OIC Server when the client sends:
            an invalid or not supported CRID channelid.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: channelchange
            example: |
              {
                "id":          "unique_example_id",
                "channelid":   "crid://localhost/1",
                "channelname": "OCF TV",
                "channelstatus": "OK",
                "channelepg":  [
                  {
                    "programname": "AVTG call",
                    "programdescription": "Weekly teleconference of the Audio Video Task Group",
                    "contenttype": {
                        "category": "Movie",
                        "subcategory": "Science fiction"
                    },
                    "contentrating": 18,
                    "programstarttime": "2018-03-13T06:00-08:00",
                    "programendtime": "2018-03-13T07:00-08:00"
                  },
                  {
                    "programname": "Architecture call",
                    "programdescription": "Weekly teleconference of the Architecture Task Group",
                    "contenttype": {
                        "category": "Movie",
                        "subcategory": "Science fiction"
                    },
                    "contentrating": 18,
                    "programstarttime": "2018-03-13T07:00-08:00",
                    "programendtime": "2018-03-13T09:00-08:00"
                  }
                ],
                "lastAction":  "channelup",
                "actions" :    [
                  {
                    "action": "channelup",
                    "href":   "channelchangeResURI",
                    "rel":    "self"
                  },
                  {
                    "action": "channeldown",
                    "href":   "channelchangeResURI",
                    "rel":    "self"
                  }
                ]
              }
