#%RAML 0.8
title: OICMediaVideo
version: v1.1.0-20180418
documentation:
  - title: © 2018 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - MediaVideo: !include oic.r.media.video.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.rw","oic.if.baseline"]

/MediaVideoResURI:
  description: |
    This resource specifies the media types that an OCF Server supports.
    The resource is an array of media elements.  Each element contains:
        A URL at which the specified media type can be accessed.
        A string array containing the definition of the media using SDP.
        Each entry in the sdp array is an SDP line.
        Each line shall follow the SDP description syntax as defined in the SDP specification.
        datetime is using RFC3339 date-time format.\n\r (e.g: '2018-06-23T20:22:59Z' - Date+Time+Timezone'UTC' or '2018-06-23T20:22:59-08:00' - Date+Time+Timezone'PST')
    The SDP specification can be found at http://tools.ietf.org/html/rfc4566.

  displayName: Media Video
  is: [ interface ]

  get:
    description: |
      Retrieves the current media video resource.
    responses:
      200:
        body:
          application/json:
            schema: MediaVideo
            example: |
              {
              "rt": ["oic.r.media.video"],
              "id": "unique_example_id",
              "title": "Video 1",
              "description": "Long user-friendly synopsis of Video 1",
              "mime_type": "video/mp4",
              "media_file": "file://example/url/Video1.mp4",
              "datetime": "2018-06-23T20:22:59-08:00",
              "media_artwork": [
                {
                  "href": "/local-video1_artwork",
                  "mimetype": "image/png",
                  "width": 256,
                  "height": 256,
                  "media": "file://example/url/video1.png",
                  "rel": "icon",
                  "ins": "uuid:UUID",
                  "rt": ["oic.r.icon"],
                  "if": ["oic.if.r"]
                  }
                ],
                "sdp": [
                  "m=video 51372 RTP/AVP 99",
                  "a=rtpmap:99 h263-1998/90000"
                  ],
                "duration": "01:22:59",
                "producers": [
                  "Producer 1",
                  "Producer 2"
                  ],
                "composers": [
                  "Composer 1",
                  "Composer 2"
                    ],
                "cast": [
                  "Actor 1",
                  "Actress 2"
                  ],
                "directors": [
                  "Dircector 1",
                  "Director 2"
                  ],
                "studio": [
                  "Studio 1",
                  "Studio 2"
                  ],
                "writers": [
                  "Writer 1",
                  "Writer 2"
                  ],
                "series": [
                  "Series 1",
                  "Series 2"
                    ],
                "format": "digital video",
                "location": "Death Valley National Park, Furnace Creek, CA 92328, USA",
                "geolocation": {"latitude": 36.4643308,"longitude": -116.86906640000001, "alt": -62.1},
                "genres": ["action & adventure", "western"],
                "rating_info": [{"rating_organization": "MPAA"}, {"rating": "PG-13"}],
                "identification_number": "EDID:1234-5678",
                "current_language": "english"
              }
