#%RAML 0.8
title: OICMediaControl
version: v1.1.0-20181030
documentation:
  - title: © 2018 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - MediaControl:       !include oic.r.media.control.json
  - MediaControlUpdate: !include oic.r.media.control-update.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.rw","oic.if.baseline"]
  - QplayState:
        queryParameters:
            play_state:
                type: boolean
  - QmediaSpeed:
        queryParameters:
            media_speed:
                type: number
  - QmediaLocation:
        queryParameters:
            media_location:
                type: number

/MediaControlResURI:
  description: |
    This resource specifies the media control capabilities of a device.
  displayName: Media Control

  get:
    is: [ interface]
    description: |
      Retrieves the current media control settings.
      Current state is "play" therefore play will not be in response as a transitions.
      The transitions from "play" are the following:
      - stop
      - pause
      - fastforward (trick modes) change, using uri templates:
        https://tools.ietf.org/html/rfc6570
        where the expanded url will be:
        mediaControlResURI?media_speed=2.5
        where the "allowed_speed_values" gives the list of allowed values for the substitution
      - rewind (trick modes) change, using uri templates:
        https://tools.ietf.org/html/rfc6570
        where the expanded url will be:
        mediaControlResURI?media_speed=-0.5
        where the "allowed_speed_values" gives the list of allowed values for the substitution
      - stepforward (trick modes) change, using uri templates:
        https://tools.ietf.org/html/rfc6570
        where the expanded url will be:
        mediaControlResURI?media_location=2.5
        where the "range_number" gives the range of allowed values and "step_number" give step increment for the substitution
      - stepbackward (trick modes) change, using uri templates:
        https://tools.ietf.org/html/rfc6570
        where the expanded url will be:
        mediaControlResURI?media_location=-0.5
        where the "range_number" gives the range of allowed values and "step_number" give step increment for the substitution
      - seek (location change), using uri templates:
        https://tools.ietf.org/html/rfc6570
        where the expanded url will be:
        mediaControlResURI?media_location=53
        where the "range_number" gives the range of allowed values for the substitution
    responses:
      200:
        body:
          application/json:
            schema: MediaControl
            example: |
              {
                "rt":           ["oic.r.media.control"],
                "id":           "unique_example_id",
                "play_state":    true,
                "media_speed":    1.0,
                "media_location": 53,
                "last_action":    "play",
                "actions" :  [
                  {
                    "action": "stop",
                    "href": "mediaControlResURI?play_state=false&media_speed=0&media_location=0"
                  },
                  {
                    "action": "pause",
                    "href": "mediaControlResURI?play_state=false"
                  },
                  {
                    "action": "fastforward",
                    "allowed_speed_values" : [ 0.5, 2.5, 5],
                    "href": "mediaControlResURI?{?media_speed}"
                  },
                  {
                    "action": "rewind",
                    "allowed_speed_values" : [ -0.5, -2.5, -5],
                    "href": "mediaControlResURI?{?media_speed}"
                  },
                  {
                    "action": "stepforward",
                    "range_number" : [ 0, 20],
                    "step_number" : 1,
                    "href": "mediaControlResURI?{?media_location}"
                  },
                  {
                    "action": "stepbackward",
                    "range_number" : [ 0, 20],
                    "step_number" : 1,
                    "href": "mediaControlResURI?{?media_location}"
                  },
                  {
                    "action": "seek",
                    "range_number" : [ 0, 3000],
                    "href": "mediaControlResURI?{?media_location}"
                  }
               ]
              }

  post:
    is: [ interface, QmediaSpeed, QplayState, QmediaLocation ]
    description: |
      Sets the current media control values
    body:
      application/json:
        schema: MediaControlUpdate
        example: |
          {
          "id":           "unique_example_id",
          "play_state":    true,
          "media_speed":    8.0,
          "media_location": 40,
          "last_action":    "fastforward"
          }
    responses:
      200:
        body:
          application/json:
            schema: MediaControlUpdate
            example: |
              {
              "id":           "unique_example_id",
              "play_state":    true,
              "media_speed":    8.0,
              "media_location":  40,
              "last_action":    "fastforward",
              "actions" : [
              {
              "action": "stop",
              "href": "mediaControlResURI?play_state=false&media_speed=0&media_location=0"
              },
              {
                "action": "play",
                "href": "mediaControlResURI?media_speed=0"
              },
              {
                "action": "pause",
                "href": "mediaControlResURI?play_state=false"
              },
              {
                "action": "rewind",
                "allowed_speed_values" : [ -0.5, -2.5, -5],
                "href": "mediaControlResURI?{?media_speed}"
              },
              {
                "action": "stepforward",
                "range_number" : [ 0, 20],
                "step_number" : 1,
                "href": "mediaControlResURI?{?media_location}"
              },
              {
                "action": "stepbackward",
                "range_number" : [ 0, 20],
                "step_number" : 1,
                "href": "mediaControlResURI?{?media_location}"
              },
              {
                "action": "seek",
                "range_number" : [ 0, 3000],
                "href": "mediaControlResURI?{?media_location}"
              }
              ]
              }
