#%RAML 0.8
title: OICMediaList
version: v1.1.0-20180323
documentation:
  - title: © 2018 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - MediaList: !include oic.r.media.list.json
  - MediaListUpdate: !include oic.r.media.list-update.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.rw","oic.if.baseline"]

/mediaListResURI:
  description: |
    This resource specifies the media list capabilities of a device.
  displayName: Media List

  get:
    is: [ interface]
    description: |
      This resource specifies a list of media or other media lists that an OCF Server supports.
        title: A human readable title for the media list.
        media_list: An array of media elements.  Each element contains:
            title: A human readable name for the media.
            url: A URL at which the specified media type can be accessed.
        The media list can support multiple modes.
        current_item: This is the current item selected.
        item_list: Is an array showing the list of indices and the arranged order of the media list.
        media_list_artwork: Is an array of artwork that is associated to the media list.
        actions: Is an array actions that are suppported with media list.

    responses:
      200:
        body:
          application/json:
            schema: MediaList
            example: |
              {
                "rt": ["oic.r.media.list"],
                "id": "unique_example_id",
                "title": "My Playlist",
                "media_list": [
                  {
                    "title": "Song 1",
                    "description": "Long user-friendly synopsis of Song 1",
                    "url": "/example/url/1",
                    "sdp": [
                      "m=audio 2 RTP/AVP 97",
                      "a=rtpmap:97 MP4A-LATM/90000"
                      ],
                      "media_artwork": [
                        {
                          "href": "/local-song1_artwork",
                          "mimetype": "image/png",
                          "width": 256,
                          "height": 256,
                          "media": "file://example/url/song1.png",
                          "rel": "icon",
                          "ins": "uuid:UUID",
                          "rt": ["oic.r.icon"],
                          "if": ["oic.if.r"]
                        }
                      ]
                  },
                  {
                    "title": "Song 2",
                    "description": "Long user-friendly synopsis of Song 2",
                    "url": "/example/url/2",
                    "sdp": [
                      "m=audio 2 RTP/AVP 97",
                      "a=rtpmap:97 MP4A-LATM/90000"
                      ],
                      "media_artwork": [
                        {
                          "href": "/web-song2_artwork",
                          "mimetype": "image/png",
                          "width": 256,
                          "height": 256,
                          "media": "http://example/url/song2.png",
                          "rel": "icon",
                          "ins": "uuid:UUID",
                          "rt": ["oic.r.icon"],
                          "if": ["oic.if.r"]
                        }
                      ]
                  },
                  {
                    "title": "Song 3",
                    "description": "Long user-friendly synopsis of Song 3",
                    "url": "/example/url/3",
                    "sdp": [
                      "m=audio 2 RTP/AVP 97",
                      "a=rtpmap:97 MP4A-LATM/90000"
                      ],
                      "media_artwork": [
                        {
                          "href": "/local-song3_artwork",
                          "mimetype": "image/png",
                          "width": 256,
                          "height": 256,
                          "media": "file://example/url/song3.png",
                          "rel": "icon",
                          "ins": "uuid:UUID",
                          "rt": ["oic.r.icon"],
                          "if": ["oic.if.r"]
                        }
                      ]
                  },
                  {
                    "title": "Song 4",
                    "description": "Long user-friendly synopsis of Song 4",
                    "url": "/example/url/4",
                    "sdp": [
                      "m=audio 2 RTP/AVP 97",
                      "a=rtpmap:97 MP4A-LATM/90000"
                      ],
                      "media_artwork": [
                        {
                          "href": "/web-song4_artwork",
                          "mimetype": "image/png",
                          "width": 256,
                          "height": 256,
                          "media": "http://example/url/song4.png",
                          "rel": "icon",
                          "ins": "uuid:UUID",
                          "rt": ["oic.r.icon"],
                          "if": ["oic.if.r"]
                        }
                      ]
                  }
                ],
                "current_item": 1,
                "item_list": [0, 1, 2, 3],
                "media_list_artwork" : [
                  {
                    "href": "/web-media_list_artwork",
                    "mimetype": "image/png",
                    "width": 256,
                    "height": 256,
                    "media": "http://findbetter.ru/public/uploads/1481662800/2043.png",
                    "rel": "icon",
                    "ins": "uuid:UUID",
                    "rt": ["oic.r.icon"],
                    "if": ["oic.if.r"]
                  },
                  {
                    "href": "/local-media_list_artwork",
                    "mimetype": "image/png",
                    "width": 64,
                    "height": 64,
                    "media": "file://example/url/sample.png",
                    "rel": "icon",
                    "ins": "uuid:UUID",
                    "rt": ["oic.r.icon"],
                    "if": ["oic.if.r"]
                  }
                ],
                "actions" :  [
                  {
                    "action": "next",
                    "href": "mediaListResURI?currentitem=nextitem",
                    "rel":   "self"
                  },
                  {
                    "action": "insert",
                    "href": "mediaListResURI?currentitem=nextitem",
                    "rel":   "self"
                  },
                  {
                    "action": "delete",
                    "href": "mediaListResURI?currentitem=nextitem",
                    "rel":   "self"
                  },
                  {
                    "action": "append",
                    "href": "mediaListResURI?currentitem=nextitem",
                    "rel":   "self"
                  },
                  {
                    "action": "previous",
                    "href": "mediaListResURI?currentitem=lastitem",
                    "rel":   "self"
                  },
                  {
                    "action": "select",
                    "href": "mediaListResURI?currentitem=3",
                    "rel":   "self"
                  }
               ]
              }

  post:
    is: [ interface ]
    description: |
      Sets the current media list values
    body:
      application/json:
        schema: MediaListUpdate
        example: |
          {
          "id":            "unique_example_id",
          "current_item":   3
          }
    responses:
      200:
        body:
          application/json:
            schema: MediaListUpdate
            example: |
              {
              "rt": ["oic.r.media.list"],
              "id": "unique_example_id",
              "title": "My Playlist",
              "media_list": [
                {
                  "title": "Song 1",
                  "description": "Long user-friendly synopsis of Song 1",
                  "url": "/example/url/1",
                  "sdp": [
                    "m=audio 2 RTP/AVP 97",
                    "a=rtpmap:97 MP4A-LATM/90000"
                    ],
                    "media_artwork": [
                      {
                        "href": "/local-song1_artwork",
                        "mimetype": "image/png",
                        "width": 256,
                        "height": 256,
                        "media": "file://example/url/song1.png",
                        "rel": "icon",
                        "ins": "uuid:UUID",
                        "rt": ["oic.r.icon"],
                        "if": ["oic.if.r"]
                      }
                    ]
                },
                {
                  "title": "Song 2",
                  "description": "Long user-friendly synopsis of Song 2",
                  "url": "/example/url/2",
                  "sdp": [
                    "m=audio 2 RTP/AVP 97",
                    "a=rtpmap:97 MP4A-LATM/90000"
                    ],
                    "media_artwork": [
                      {
                        "href": "/web-song2_artwork",
                        "mimetype": "image/png",
                        "width": 256,
                        "height": 256,
                        "media": "http://example/url/song2.png",
                        "rel": "icon",
                        "ins": "uuid:UUID",
                        "rt": ["oic.r.icon"],
                        "if": ["oic.if.r"]
                      }
                    ]
                },
                {
                  "title": "Song 3",
                  "description": "Long user-friendly synopsis of Song 3",
                  "url": "/example/url/3",
                  "sdp": [
                    "m=audio 2 RTP/AVP 97",
                    "a=rtpmap:97 MP4A-LATM/90000"
                    ],
                    "media_artwork": [
                      {
                        "href": "/local-song3_artwork",
                        "mimetype": "image/png",
                        "width": 256,
                        "height": 256,
                        "media": "file://example/url/song3.png",
                        "rel": "icon",
                        "ins": "uuid:UUID",
                        "rt": ["oic.r.icon"],
                        "if": ["oic.if.r"]
                      }
                    ]
                },
                {
                  "title": "Song 4",
                  "description": "Long user-friendly synopsis of Song 4",
                  "url": "/example/url/4",
                  "sdp": [
                    "m=audio 2 RTP/AVP 97",
                    "a=rtpmap:97 MP4A-LATM/90000"
                    ],
                    "media_artwork": [
                      {
                        "href": "/web-song4_artwork",
                        "mimetype": "image/png",
                        "width": 256,
                        "height": 256,
                        "media": "http://example/url/song4.png",
                        "rel": "icon",
                        "ins": "uuid:UUID",
                        "rt": ["oic.r.icon"],
                        "if": ["oic.if.r"]
                      }
                    ]
                }
              ],
              "current_item":   3,
              "item_list": [0, 1, 2, 3],
              "media_list_artwork" : [
                {
                  "href": "/web-media_list_artwork",
                  "mimetype": "image/png",
                  "width": 256,
                  "height": 256,
                  "media": "http://findbetter.ru/public/uploads/1481662800/2043.png",
                  "rel": "icon",
                  "ins": "uuid:UUID",
                  "rt": ["oic.r.icon"],
                  "if": ["oic.if.r"]
                },
                {
                  "href": "/local-media_list_artwork",
                  "mimetype": "image/png",
                  "width": 64,
                  "height": 64,
                  "media": "file://example/url/sample.png",
                  "rel": "icon",
                  "ins": "uuid:UUID",
                  "rt": ["oic.r.icon"],
                  "if": ["oic.if.r"]
                }
              ],
              "actions" :  [
                {
                  "action": "next",
                  "href": "mediaListResURI?currentitem=nextitem",
                  "rel":   "self"
                },
                {
                  "action": "insert",
                  "href": "mediaListResURI?currentitem=nextitem",
                  "rel":   "self"
                },
                {
                  "action": "delete",
                  "href": "mediaListResURI?currentitem=nextitem",
                  "rel":   "self"
                },
                {
                  "action": "append",
                  "href": "mediaListResURI?currentitem=nextitem",
                  "rel":   "self"
                },
                {
                  "action": "previous",
                  "href": "mediaListResURI?currentitem=lastitem",
                  "rel":   "self"
                },
                {
                  "action": "select",
                  "href": "mediaListResURI?currentitem=3",
                  "rel":   "self"
                }
              ]
              }
